### ISSUE TITLE
[Info] Mod Compatibility Issues

### ISSUE THREAD

**Issue by Dragon-Seeker** [wisp-forest/accessories#25]
Below is a list of all current mod incompatibilities that are present with the Compatibility Layers and the corresponding Issues:

- [x] ~~Inventory Hud+ [[Link](https://www.curseforge.com/minecraft/mc-mods/inventory-hud-forge)] - Crashes or lags game with errors [[Issue](https://github.com/wisp-forest/accessories/issues/4)]~~ Fixed
- [x] ~~Sophisticated Backpacks (Unoffical Fabric port) [[Link](https://modrinth.com/mod/sophisticated-backpacks-(unoffical-fabric-port)/gallery)] - Various aspects of equipping and general use case within Accessories Slot is broken [[Issue](https://github.com/wisp-forest/accessories/issues/20)]~~ Fixed
- [ ] Inventorio [Forge/Fabric] [[Link](https://www.curseforge.com/minecraft/mc-mods/inventorio-forge)] - Crashes out right or issues involved with opening inventory leading to inability to open the screen [[Issue](https://github.com/wisp-forest/accessories/issues/24)]

**Comment by Galysso** [comment]
Am I able to help you somehow?

**Comment by Dragon-Seeker** [comment]
> Am I able to help you somehow?

This page is here to act as a list for all the problematic mods that are incompatible with fixes needing to be placed either on me with specific mixins that I can't sustain forever or for the mod authors to support Accessories API figuring a way to enable such when even detecting compat layers.
